version: "3"

services:

  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
      - db

  web:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"

