"""empty message

Revision ID: ffc5d273c738
Revises: 
Create Date: 2023-02-27 13:44:13.335440

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ffc5d273c738"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "friends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("initiator_user_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "state",
            sa.Enum("Requested", "Blocked", "Approved", name="friendsstate"),
            nullable=True,
        ),
        sa.Column("blocked_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["initiator_user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("initiator_user_id", "user_id", name="unfriend"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friends")
    op.drop_table("users")
    # ### end Alembic commands ###
