"""empty message

Revision ID: 201b1806afdd
Revises: 9d0f4b8fd381
Create Date: 2023-03-02 11:17:19.082955

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "201b1806afdd"
down_revision = "9d0f4b8fd381"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unname", "file", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unname", "file", type_="unique")
    # ### end Alembic commands ###
