"""empty message

Revision ID: 756d119923eb
Revises: 5a878a5c7cf6
Create Date: 2023-03-01 18:01:38.981757

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "756d119923eb"
down_revision = "5a878a5c7cf6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("storage", sa.Column("maxium_space_gb", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("storage", "maxium_space_gb")
    # ### end Alembic commands ###
