"""empty message

Revision ID: 9e0b4c8d583f
Revises: 154698e9c9d9
Create Date: 2023-03-01 17:43:02.277582

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9e0b4c8d583f"
down_revision = "154698e9c9d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
