"""empty message

Revision ID: b948eabf88e0
Revises: 9e0b4c8d583f
Create Date: 2023-03-01 17:53:34.024209

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b948eabf88e0"
down_revision = "9e0b4c8d583f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
