"""empty message

Revision ID: e9efa3d685f6
Revises: eb88565f117e
Create Date: 2023-03-02 08:55:19.288759

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e9efa3d685f6"
down_revision = "eb88565f117e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("name", sa.String(), nullable=True))
    op.add_column("file", sa.Column("uploaded_at", sa.DateTime(), nullable=True))
    op.add_column("file", sa.Column("last_downloaded_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "last_downloaded_at")
    op.drop_column("file", "uploaded_at")
    op.drop_column("file", "name")
    # ### end Alembic commands ###
