"""empty message

Revision ID: ef702b24c36e
Revises: fce024570efa
Create Date: 2023-02-27 16:30:41.201693

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef702b24c36e"
down_revision = "fce024570efa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("friends", "blocked_by")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "friends",
        sa.Column("blocked_by", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
